services:
  mach1_robot:
    build:
      context: ..
      # TODO: This might need to be updated to support .dev/.prod and update the RELAVATIVE path
      dockerfile: docker/Dockerfile.dev
      args:
        - USERNAME=${CONTAINER_USER}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_HOSTNAME}
    environment:
      - REMOTE_IP=${REMOTE_IP_ADDR}
      - REMOTE_HOST=${REMOTE_HOSTNAME}
    networks:
      mynetwork:
        ipv4_address: ${CONTAINER_STATIC_IP}
    volumes:
      # - ../../machx_code:/home/${CONTAINER_USER}/machx_code
      - ../volumes/entrypoint.sh:/home/${CONTAINER_USER}/entrypoint.sh
      - ../volumes/hosts:/etc/hosts
    entrypoint: ["/home/${CONTAINER_USER}/entrypoint.sh"]

networks:
  mynetwork:
    ipam:
      config:
        - subnet: ${CONTAINER_SUBNET}
